
user_request = [
    "source_satellite_plane_id",
    "source_satellite_iner_plane_pos_id",
    "service_1",
    "service_2",
    "service_3",
    "destination_satellite_plane_id",
    "destination_satellite_iner_plane_pos_id",
    "arrival_time",
    "data_volume_1",
    "data_volume_2",
    "data_volume_3",
    "data_volume_4",
    "service_1_serving_satellite_id",
    "service_2_serving_satellite_id",
    "service_3_serving_satellite_id",
    "accumulated_latency",
    "accumulated_energy",
    "execution_stage",
    "execution_time_slot"
]

satellite_link_state = [
    [
        "source_satellite_plane_id",
        "source_satellite_iner_plane_pos_id",
        "source_satellite_computing_capacity(flops)",
        "source_satellite_computing_capacity_efficiency((0,1])",
        "source_satellite_computing_queue_length",
        "source_satellite_computing_rate_power(Wt)",
        "source_satellite_ISL-1_available",
        "source_satellite_ISL-1_transmission_rate",
        "source_satellite_ISL-1_transmission_rate_efficiency((0,1])",
        "source_satellite_ISL-1_transmission_queue_length",
        "source_satellite_ISL-1_transmission_rate_power(Wt)",
        "source_satellite_ISL-1_distance",
        "source_satellite_ISL-2_available",
        "source_satellite_ISL-2_transmission_rate",
        "source_satellite_ISL-2_transmission_rate_efficiency((0,1])",
        "source_satellite_ISL-2_transmission_queue_length",
        "source_satellite_ISL-2_transmission_rate_power(Wt)",
        "source_satellite_ISL-2_distance",
        "source_satellite_ISL-3_available",
        "source_satellite_ISL-3_transmission_rate",
        "source_satellite_ISL-3_transmission_rate_efficiency((0,1])",
        "source_satellite_ISL-3_transmission_queue_length",
        "source_satellite_ISL-3_transmission_rate_power(Wt)",
        "source_satellite_ISL-3_distance",
        "source_satellite_ISL-4_available",
        "source_satellite_ISL-4_transmission_rate",
        "source_satellite_ISL-4_transmission_rate_efficiency((0,1])",
        "source_satellite_ISL-4_transmission_queue_length",
        "source_satellite_ISL-4_transmission_rate_power(Wt)",
        "source_satellite_ISL-4_distance",
        "host_current_service",
        "time_slot"
    ],
    [
        "satellite_1_plane_id",
        "satellite_1_iner_plane_pos_id",
        "satellite_1_computing_capacity(flops)",
        "satellite_1_computing_capacity_efficiency((0,1])",
        "satellite_1_computing_queue_length",
        "satellite_1_computing_rate_power(Wt)",
        "satellite_1_ISL-1_available",
        "satellite_1_ISL-1_transmission_rate",
        "satellite_1_ISL-1_transmission_rate_efficiency((0,1])",
        "satellite_1_ISL-1_transmission_queue_length",
        "satellite_1_ISL-1_transmission_rate_power(Wt)",
        "satellite_1_ISL-1_distance",
        "satellite_1_ISL-2_available",
        "satellite_1_ISL-2_transmission_rate",
        "satellite_1_ISL-2_transmission_rate_efficiency((0,1])",
        "satellite_1_ISL-2_transmission_queue_length",
        "satellite_1_ISL-2_transmission_rate_power(Wt)",
        "satellite_1_ISL-2_distance",
        "satellite_1_ISL-3_available",
        "satellite_1_ISL-3_transmission_rate",
        "satellite_1_ISL-3_transmission_rate_efficiency((0,1])",
        "satellite_1_ISL-3_transmission_queue_length",
        "satellite_1_ISL-3_transmission_rate_power(Wt)",
        "satellite_1_ISL-3_distance",
        "satellite_1_ISL-4_available",
        "satellite_1_ISL-4_transmission_rate",
        "satellite_1_ISL-4_transmission_rate_efficiency((0,1])",
        "satellite_1_ISL-4_transmission_queue_length",
        "satellite_1_ISL-4_transmission_rate_power(Wt)",
        "satellite_1_ISL-4_distance",
        "host_current_service",
        "time_slot"
    ],
    [
        "satellite_2_plane_id",
        "satellite_2_iner_plane_pos_id",
        "satellite_2_computing_capacity(flops)",
        "satellite_2_computing_capacity_efficiency((0,1])",
        "satellite_2_computing_queue_length",
        "satellite_2_computing_rate_power(Wt)",
        "satellite_2_ISL-1_available",
        "satellite_2_ISL-1_transmission_rate",
        "satellite_2_ISL-1_transmission_rate_efficiency((0,1])",
        "satellite_2_ISL-1_transmission_queue_length",
        "satellite_2_ISL-1_transmission_rate_power(Wt)",
        "satellite_2_ISL-1_distance",
        "satellite_2_ISL-2_available",
        "satellite_2_ISL-2_transmission_rate",
        "satellite_2_ISL-2_transmission_rate_efficiency((0,1])",
        "satellite_2_ISL-2_transmission_queue_length",
        "satellite_2_ISL-2_transmission_rate_power(Wt)",
        "satellite_2_ISL-2_distance",
        "satellite_2_ISL-3_available",
        "satellite_2_ISL-3_transmission_rate",
        "satellite_2_ISL-3_transmission_rate_efficiency((0,1])",
        "satellite_2_ISL-3_transmission_queue_length",
        "satellite_2_ISL-3_transmission_rate_power(Wt)",
        "satellite_2_ISL-3_distance",
        "satellite_2_ISL-4_available",
        "satellite_2_ISL-4_transmission_rate",
        "satellite_2_ISL-4_transmission_rate_efficiency((0,1])",
        "satellite_2_ISL-4_transmission_queue_length",
        "satellite_2_ISL-4_transmission_rate_power(Wt)",
        "satellite_2_ISL-4_distance",
        "host_current_service",
        "time_slot"
    ],
    [
        "satellite_3_plane_id",
        "satellite_3_iner_plane_pos_id",
        "satellite_3_computing_capacity(flops)",
        "satellite_3_computing_capacity_efficiency((0,1])",
        "satellite_3_computing_queue_length",
        "satellite_3_computing_rate_power(Wt)",
        "satellite_3_ISL-1_available",
        "satellite_3_ISL-1_transmission_rate",
        "satellite_3_ISL-1_transmission_rate_efficiency((0,1])",
        "satellite_3_ISL-1_transmission_queue_length",
        "satellite_3_ISL-1_transmission_rate_power(Wt)",
        "satellite_3_ISL-1_distance",
        "satellite_3_ISL-2_available",
        "satellite_3_ISL-2_transmission_rate",
        "satellite_3_ISL-2_transmission_rate_efficiency((0,1])",
        "satellite_3_ISL-2_transmission_queue_length",
        "satellite_3_ISL-2_transmission_rate_power(Wt)",
        "satellite_3_ISL-2_distance",
        "satellite_3_ISL-3_available",
        "satellite_3_ISL-3_transmission_rate",
        "satellite_3_ISL-3_transmission_rate_efficiency((0,1])",
        "satellite_3_ISL-3_transmission_queue_length",
        "satellite_3_ISL-3_transmission_rate_power(Wt)",
        "satellite_3_ISL-3_distance",
        "satellite_3_ISL-4_available",
        "satellite_3_ISL-4_transmission_rate",
        "satellite_3_ISL-4_transmission_rate_efficiency((0,1])",
        "satellite_3_ISL-4_transmission_queue_length",
        "satellite_3_ISL-4_transmission_rate_power(Wt)",
        "satellite_3_ISL-4_distance",
        "host_current_service",
        "time_slot"
    ],
    [
        "satellite_4_plane_id",
        "satellite_4_iner_plane_pos_id",
        "satellite_4_computing_capacity(flops)",
        "satellite_4_computing_capacity_efficiency((0,1])",
        "satellite_4_computing_queue_length",
        "satellite_4_computing_rate_power(Wt)",
        "satellite_4_ISL-1_available",
        "satellite_4_ISL-1_transmission_rate",
        "satellite_4_ISL-1_transmission_rate_efficiency((0,1])",
        "satellite_4_ISL-1_transmission_queue_length",
        "satellite_4_ISL-1_transmission_rate_power(Wt)",
        "satellite_4_ISL-1_distance",
        "satellite_4_ISL-2_available",
        "satellite_4_ISL-2_transmission_rate",
        "satellite_4_ISL-2_transmission_rate_efficiency((0,1])",
        "satellite_4_ISL-2_transmission_queue_length",
        "satellite_4_ISL-2_transmission_rate_power(Wt)",
        "satellite_4_ISL-2_distance",
        "satellite_4_ISL-3_available",
        "satellite_4_ISL-3_transmission_rate",
        "satellite_4_ISL-3_transmission_rate_efficiency((0,1])",
        "satellite_4_ISL-3_transmission_queue_length",
        "satellite_4_ISL-3_transmission_rate_power(Wt)",
        "satellite_4_ISL-3_distance",
        "satellite_4_ISL-4_available",
        "satellite_4_ISL-4_transmission_rate",
        "satellite_4_ISL-4_transmission_rate_efficiency((0,1])",
        "satellite_4_ISL-4_transmission_queue_length",
        "satellite_4_ISL-4_transmission_rate_power(Wt)",
        "satellite_4_ISL-4_distance",
        "host_current_service",
        "time_slot"
    ],
    [
        "satellite_5_plane_id",
        "satellite_5_iner_plane_pos_id",
        "satellite_5_computing_capacity(flops)",
        "satellite_5_computing_capacity_efficiency((0,1])",
        "satellite_5_computing_queue_length",
        "satellite_5_computing_rate_power(Wt)",
        "satellite_5_ISL-1_available",
        "satellite_5_ISL-1_transmission_rate",
        "satellite_5_ISL-1_transmission_rate_efficiency((0,1])",
        "satellite_5_ISL-1_transmission_queue_length",
        "satellite_5_ISL-1_transmission_rate_power(Wt)",
        "satellite_5_ISL-1_distance",
        "satellite_5_ISL-2_available",
        "satellite_5_ISL-2_transmission_rate",
        "satellite_5_ISL-2_transmission_rate_efficiency((0,1])",
        "satellite_5_ISL-2_transmission_queue_length",
        "satellite_5_ISL-2_transmission_rate_power(Wt)",
        "satellite_5_ISL-2_distance",
        "satellite_5_ISL-3_available",
        "satellite_5_ISL-3_transmission_rate",
        "satellite_5_ISL-3_transmission_rate_efficiency((0,1])",
        "satellite_5_ISL-3_transmission_queue_length",
        "satellite_5_ISL-3_transmission_rate_power(Wt)",
        "satellite_5_ISL-3_distance",
        "satellite_5_ISL-4_available",
        "satellite_5_ISL-4_transmission_rate",
        "satellite_5_ISL-4_transmission_rate_efficiency((0,1])",
        "satellite_5_ISL-4_transmission_queue_length",
        "satellite_5_ISL-4_transmission_rate_power(Wt)",
        "satellite_5_ISL-4_distance",
        "host_current_service",
        "time_slot"
    ],
    [
        "satellite_6_plane_id",
        "satellite_6_iner_plane_pos_id",
        "satellite_6_computing_capacity(flops)",
        "satellite_6_computing_capacity_efficiency((0,1])",
        "satellite_6_computing_queue_length",
        "satellite_6_computing_rate_power(Wt)",
        "satellite_6_ISL-1_available",
        "satellite_6_ISL-1_transmission_rate",
        "satellite_6_ISL-1_transmission_rate_efficiency((0,1])",
        "satellite_6_ISL-1_transmission_queue_length",
        "satellite_6_ISL-1_transmission_rate_power(Wt)",
        "satellite_6_ISL-1_distance",
        "satellite_6_ISL-2_available",
        "satellite_6_ISL-2_transmission_rate",
        "satellite_6_ISL-2_transmission_rate_efficiency((0,1])",
        "satellite_6_ISL-2_transmission_queue_length",
        "satellite_6_ISL-2_transmission_rate_power(Wt)",
        "satellite_6_ISL-2_distance",
        "satellite_6_ISL-3_available",
        "satellite_6_ISL-3_transmission_rate",
        "satellite_6_ISL-3_transmission_rate_efficiency((0,1])",
        "satellite_6_ISL-3_transmission_queue_length",
        "satellite_6_ISL-3_transmission_rate_power(Wt)",
        "satellite_6_ISL-3_distance",
        "satellite_6_ISL-4_available",
        "satellite_6_ISL-4_transmission_rate",
        "satellite_6_ISL-4_transmission_rate_efficiency((0,1])",
        "satellite_6_ISL-4_transmission_queue_length",
        "satellite_6_ISL-4_transmission_rate_power(Wt)",
        "satellite_6_ISL-4_distance",
        "host_current_service",
        "time_slot"
    ],
    [
        "satellite_7_plane_id",
        "satellite_7_iner_plane_pos_id",
        "satellite_7_computing_capacity(flops)",
        "satellite_7_computing_capacity_efficiency((0,1])",
        "satellite_7_computing_queue_length",
        "satellite_7_computing_rate_power(Wt)",
        "satellite_7_ISL-1_available",
        "satellite_7_ISL-1_transmission_rate",
        "satellite_7_ISL-1_transmission_rate_efficiency((0,1])",
        "satellite_7_ISL-1_transmission_queue_length",
        "satellite_7_ISL-1_transmission_rate_power(Wt)",
        "satellite_7_ISL-1_distance",
        "satellite_7_ISL-2_available",
        "satellite_7_ISL-2_transmission_rate",
        "satellite_7_ISL-2_transmission_rate_efficiency((0,1])",
        "satellite_7_ISL-2_transmission_queue_length",
        "satellite_7_ISL-2_transmission_rate_power(Wt)",
        "satellite_7_ISL-2_distance",
        "satellite_7_ISL-3_available",
        "satellite_7_ISL-3_transmission_rate",
        "satellite_7_ISL-3_transmission_rate_efficiency((0,1])",
        "satellite_7_ISL-3_transmission_queue_length",
        "satellite_7_ISL-3_transmission_rate_power(Wt)",
        "satellite_7_ISL-3_distance",
        "satellite_7_ISL-4_available",
        "satellite_7_ISL-4_transmission_rate",
        "satellite_7_ISL-4_transmission_rate_efficiency((0,1])",
        "satellite_7_ISL-4_transmission_queue_length",
        "satellite_7_ISL-4_transmission_rate_power(Wt)",
        "satellite_7_ISL-4_distance",
        "host_current_service",
        "time_slot"
    ],

]

constellation_satellite_link_adjacent_matrix_in_future_N_window = [
    [[0, 1, 1, 1, 1, 1, 1],
     [0, 1, 1, 1, 1, 1, 1],
     [0, 1, 1, 1, 1, 1, 1],
     [0, 1, 1, 1, 1, 1, 1],
     [0, 1, 1, 1, 1, 1, 1],
     [0, 1, 1, 1, 1, 1, 1],
     [0, 1, 1, 1, 1, 1, 1],
     [0, 1, 1, 1, 1, 1, 1]],
    [[0, 1, 1, 1, 1, 1, 1],
     [1, 1, 1, 0, 1, 1, 1],
     [1, 1, 1, 1, 1, 1, 1],
     [1, 1, 1, 1, 1, 1, 1],
     [1, 1, 1, 1, 1, 1, 1],
     [1, 1, 1, 1, 1, 1, 1],
     [1, 1, 1, 1, 1, 1, 1],
     [1, 1, 1, 1, 1, 1, 1]],
    [[0, 1, 1, 1, 1, 1, 1],
     [1, 1, 1, 0, 1, 1, 1],
     [1, 1, 1, 1, 1, 1, 1],
     [1, 1, 0, 1, 1, 1, 1],
     [1, 1, 1, 1, 1, 1, 1],
     [1, 1, 1, 1, 1, 1, 1],
     [1, 1, 1, 1, 1, 1, 1],
     [1, 1, 1, 1, 1, 1, 1]],
]


"""
Note:
1> ISL-1 表示 前向同轨星间链路; ISL-2 表示 后向同轨星间链路; ISL-3 表示 左向异轨星间链路; ISL-4 表示 右向异轨星间链路
2> constellation_satellite_link_adjacent_matrix_in_future_N_window 仅用来表示卫星节点之间星间链路在未来若干个time slot内的连通性
3> 对 satellite_link_state 中的卫星个数由用户请求链中微服务对应副本所部署的卫星总数所决定, 其中卫星节点特征中增加了一条服务部署信息，host_current_service，标明是否部署了当前执行阶段的微服务
"""

"""
将 Serving satellite selection 建模为 POMDP, 其中背景流量和计算任务信息被编码进 
0. 拟定 PPO-Agent 的状态空间由 user_request, satellite_link_state, 和 constellation_satellite_link_adjacent_matrix_in_future_N_window 三者 共同组成,
1. 拟定使用 MLP 来编码 user_request 这个向量, 得到一个 hidden states,
2. 拟定使用 MLP 来编码 constellation_satellite_link_adjacent_matrix_in_future_N_window 这个矩阵, 得到一个 hidden states,
3. 拟定使用 Attention-based encoder 来编码 satellite_link_state 这个矩阵, 然后得到一个 hidden states,
3. 将1.，2.，3. 中生成的 hidden states 进行拼接, 再经过一个 MLP, 得到 hidden state
4. 根据生成的hidden state，获取action output, 其中 PPO-Agent 的输出为一个 action logits 向量, 其长度为 N_max (论文中规定的允许最大微服务副本数), 如果某个微服务的副本数小于 N_max, 则对 action logits 进行 mask 处理, 确保最后采样出来的 action 是合法的.
5. 得到采样后的动作之后，在 a_i 上执行微服务，并得到 stage_latency, stage_energy， accumulated_latency 和 accumulated_energy, 并得到 奖励 r = -(alpha * stage_latency + beta * stage_energy)
6. 更新请求进度，i <- i + 1; u <- a_i; /tau <- /tau + stage_latency
7. 根据当前最新的 time slot, 更新 user_request, satellite_link_state, 和 constellation_satellite_link_adjacent_matrix_in_future_N_window 
"""

